// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOsKRNhWWz9I_MoZQfaU93fuDW3FrBjX0',
    appId: '1:377016718616:android:719313f55df0620f9bba6d',
    messagingSenderId: '377016718616',
    projectId: 'dayalog-33e67',
    storageBucket: 'dayalog-33e67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqqhRZcblqDqQRe6p4u9xfRil49c_l2bw',
    appId: '1:377016718616:ios:91f06c0e109d19029bba6d',
    messagingSenderId: '377016718616',
    projectId: 'dayalog-33e67',
    storageBucket: 'dayalog-33e67.appspot.com',
    iosBundleId: 'co.dayalog.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqqhRZcblqDqQRe6p4u9xfRil49c_l2bw',
    appId: '1:377016718616:ios:a85a3fd0d916b1459bba6d',
    messagingSenderId: '377016718616',
    projectId: 'dayalog-33e67',
    storageBucket: 'dayalog-33e67.appspot.com',
    iosBundleId: 'com.patasente.dayalog.dayalog',
  );
}
